language: php
php:
  - 5.3
before_script:
  - wget --quiet http://getcomposer.org/composer.phar
  - php composer.phar install
  - cp phpunit.xml.dist phpunit.xml
  - phpunit --version
script: phpunit
